# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sriram Vasudevan
tagline:          'Personal Website'
description:      '"Veni, Vidi, Vici."<br/>For the lack of a better alternative.'
url:              http://www.sriramvasudevan.com

author:
  name:           'Sriram V'
  facebook:       https://www.facebook.com/sriram.vasudevan
  twitter:        https://www.twitter.com/vasudevansriram
  google:         https://plus.google.com/+SriramV15
  github:         https://www.github.com/sriramvasudevan
  email_md5:      042d1171374bfd889c68a567872743b0

paginate:         5
paginate_path:    "posts/page:num"
